In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt



In [ ]:
dataset = pd.read_csv('spam.csv',encoding='latin-1')

In [ ]:
dataset.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB


In [ ]:
dataset.drop(columns=['Unnamed: 2','Unnamed: 3','Unnamed: 4'],inplace=True)

In [ ]:
dataset.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
for i in range(0,5572):
  sms = re.sub('[^a-zA-Z]',' ',dataset['v2'][i])
  sms = sms.lower()
  sms = sms.split()
  ps = PorterStemmer()
  allstopwords = stopwords.words('english')

  sms = [ps.stem(word) for word in sms if not word in set(allstopwords)]
  sms = ' '.join(sms)
  corpus.append(sms)

In [ ]:
corpus[1:5]

['ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though']

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2000)
X = cv.fit_transform(corpus).toarray()

In [ ]:
len(X[0])

2000

In [ ]:
X[1:5][1:5]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
y = dataset['v1'].map({'ham':0,'spam':1})

In [ ]:
print(y)

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: v1, Length: 5572, dtype: int64


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train,y_train)

GaussianNB()

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
right_pred = 0
wrong_pred = 0
for i,j in zip(y_test,y_pred):
  if i == j:
    right_pred+=1
  else:
    wrong_pred += 1

In [ ]:
print(right_pred)
print(wrong_pred)

948
167


In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
cm = confusion_matrix(y_pred,y_test)
print(cm)
print(accuracy_score(y_pred,y_test))

[[802  20]
 [147 146]]
0.8502242152466367


In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier1 = RandomForestClassifier()
classifier1.fit(X_train,y_train)

RandomForestClassifier()

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
right_pred = 0
wrong_pred = 0
for i,j in zip(y_test,y_pred):
  if i == j:
    right_pred+=1
  else:
    wrong_pred += 1

In [ ]:
print(right_pred)
print(wrong_pred)

948
167


In [ ]:
import tensorflow as tf

In [ ]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=50,activation='relu'))
ann.add(tf.keras.layers.Dense(units=50,activation='relu'))
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [ ]:
ann.compile(optimizer = 'adam' , loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
ann.fit(X_train,y_train,batch_size=42,epochs = 200)

Epoch 1/200
107/107 [==============================] - 3s 7ms/step - loss: 0.3268 - accuracy: 0.9035
Epoch 2/200
107/107 [==============================] - 1s 6ms/step - loss: 0.0497 - accuracy: 0.9874
Epoch 3/200
107/107 [==============================] - 0s 4ms/step - loss: 0.0202 - accuracy: 0.9939
Epoch 4/200
107/107 [==============================] - 1s 6ms/step - loss: 0.0098 - accuracy: 0.9973
Epoch 5/200
107/107 [==============================] - 1s 6ms/step - loss: 0.0060 - accuracy: 0.9987
Epoch 6/200
107/107 [==============================] - 1s 6ms/step - loss: 0.0040 - accuracy: 0.9993
Epoch 7/200
107/107 [==============================] - 1s 6ms/step - loss: 0.0033 - accuracy: 0.9996
Epoch 8/200
107/107 [==============================] - 0s 4ms/step - loss: 0.0028 - accuracy: 0.9996
Epoch 9/200
107/107 [==============================] - 0s 4ms/step - loss: 0.0026 - accuracy: 0.9993
Epoch 10/200
107/107 [==============================] - 0s 4ms/step - loss: 0.0024 - accura

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)

right = 0
wrong = 0
for i,j in zip(y_pred,y_test):
  if i == j:
    right+=1
  else:
    wrong+=1
print(right)
print(wrong)

35/35 [==============================] - 0s 3ms/step
1084
31


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[935  14]
 [ 17 149]]


0.9721973094170404